module.exports.ACTION = {
    ADD_CONTACT: 'ADD_CONTACT_ACTION',
    SELECT_CONTACT: 'SELECT_CONTACT_ACTION'
}

module.exports.EVENT = {
    CONTACT_LIST_UPDATED: 'CONTACT_LIST_UPDATED',
    MESSAGES_UPDATED: 'MESSAGES_UPDATED'
}